services:
  cms-app:
    build: .
    container_name: cms-app
    network_mode: host
    volumes:
      - /opt/conf:/opt/conf
      - /opt/logs/cms:/app/logs
    environment:
      - TZ=Asia/Seoul
      - BASE_PATH=/app/data
      - LOG_HOME=/app/logs
    restart: unless-stopped